### ISSUE TITLE
ModuleNotFoundError: No module named 'debug_toolbar'

### ISSUE THREAD

**Issue by Tyu-Uyt** [Bwc9876/CodeReview#73]
Following the instructions given gives me a ModuleNotFoundError.
````
(BASE) C:\Users\noble\Desktop\CodeReview-master>python manage.py runserver localhost:8080
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\noble\Desktop\CodeReview-master\BASE\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\noble\Desktop\CodeReview-master\BASE\lib\site-packages\django\core\management\commands\runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\noble\Desktop\CodeReview-master\BASE\lib\site-packages\django\utils\autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "C:\Users\noble\Desktop\CodeReview-master\BASE\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Users\noble\Desktop\CodeReview-master\BASE\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\noble\Desktop\CodeReview-master\BASE\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\noble\Desktop\CodeReview-master\BASE\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\noble\Desktop\CodeReview-master\BASE\lib\site-packages\django\apps\config.py", line 224, in create
    import_module(entry)
  File "C:\Program Files\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'debug_toolbar'

(BASE) C:\Users\noble\Desktop\CodeReview-master>^Z
(BASE) C:\Users\noble\Desktop\CodeReview-master>python manage.py runserver
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\noble\Desktop\CodeReview-master\BASE\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\noble\Desktop\CodeReview-master\BASE\lib\site-packages\django\core\management\commands\runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\noble\Desktop\CodeReview-master\BASE\lib\site-packages\django\utils\autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "C:\Users\noble\Desktop\CodeReview-master\BASE\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Users\noble\Desktop\CodeReview-master\BASE\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\noble\Desktop\CodeReview-master\BASE\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\noble\Desktop\CodeReview-master\BASE\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\noble\Desktop\CodeReview-master\BASE\lib\site-packages\django\apps\config.py", line 224, in create
    import_module(entry)
  File "C:\Program Files\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'debug_toolbar'
````

**Comment by Bwc9876** [comment]
Run the following:
```sh
pip install -r requirements.txt
python manage.py migrate
```
